### ISSUE TITLE
failed to build perse

### ISSUE THREAD

**Issue by amos77** [perses-project/perses#15]
When I build bazel, I got several returned error messages like "Error while fetching artifact with coursier: Timed out". The top-level error message is 
"INFO: Repository maven instantiated at:
  /my/home/path/projects/perses/WORKSPACE:16:14: in <toplevel>
  /bazel/tmp/dir_path/fca3721dec91925a5c679fcc769838a8/external/rules_jvm_external/defs.bzl:83:19: in maven_install
Repository rule coursier_fetch defined at:
  /bazel/tmp/dir_path/fca3721dec91925a5c679fcc769838a8/external/rules_jvm_external/coursier.bzl:852:33: in <toplevel>
INFO: Repository 'maven' used the following cache hits instead of downloading the corresponding file.
 \* Hash '2311054a07f5e8d83766155744e139e7a4b2ee1e77d47a636839687c4233a465' for https://jcenter.bintray.com/io/get-coursier/coursier-cli_2.12/1.1.0-M14-4/coursier-cli_2.12-1.1.0-M14-4-standalone.jar
If the definition of 'maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
	File "/bazel/tmp/dir_path/fca3721dec91925a5c679fcc769838a8/external/rules_jvm_external/coursier.bzl", line 660, column 13, in _coursier_fetch_impl
		fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Timed out".

I have no idea how to solve these problems.

**Comment by chengniansun** [comment]
Hmm, this is new to me, and I do not know how to solve it. 

But this should be a bazel problem. I saw your previous issue. But I am not sure whether it is because of your java version. Just for your information, I am using java 8 or 11 for development.
